name: welldone
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  get: ^4.6.5
  flutter_localizations:
    sdk: flutter
  intl: 0.18.0
  table_calendar: 3.0.9
  flutter_native_timezone_updated_gradle: ^2.0.3
  flutter_local_notifications: ^14.1.1
  flutter_easyloading: ^3.0.5
  flutter_screenutil: ^5.8.4
  path_provider: ^2.0.15
  flutter_typeahead: ^4.6.1
  iconsax: ^0.0.8
  flutter_slidable: ^3.0.0
  sleek_circular_slider: ^2.0.1
  dropdown_button2: ^1.9.2
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.5
  isar_generator: ^3.1.0+1

flutter_icons:
  android: 'launcher_icon'
  image_path: "assets/icons/well.done.png"
  ios: true
  adaptive_icon_background: "#1F1F1F"
  adaptive_icon_foreground: "assets/icons/well.done.png"

flutter_native_splash:
  color: "#1F1F1F"
#  image: "assets/icons/icons.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

fonts:
  - family: Inter
    fonts:
      - asset: assets/fonts/Inter-Black.ttf
        weight: 900
      - asset: assets/fonts/Inter-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Inter-Bold.ttf
        weight: 700
      - asset: assets/fonts/Inter-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Inter-Medium.ttf
        weight: 500
      - asset: assets/fonts/Inter-Regular.ttf
        weight: 400
      - asset: assets/fonts/Inter-Light.ttf
        weight: 300
      - asset: assets/fonts/Inter-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Inter-Thin.ttf
        weight: 100
  - family: iconsax
    fonts:
      - asset: assets/fonts/iconsax.ttf
